sudo: false
language: python

os: linux
dist: bionic

git:
  depth: 3
  submodules: false

branches:
  only:
    - master

python:
  - "3.6"
  - "3.7"
  - "nightly"

matrix:
  fast_finish: true

cache: pip

install:
  - pip install --upgrade -r requirements-dev.txt

script:
  - ./check.sh
